// resources/js/Pages/Shippers/Create.tsx
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';

export default function ShipperCreate() {
  const { data, setData, post, processing, errors } = useForm({
    name: '',
    mc_number: '',
    dot_number: '',
    status: 'active',
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    post(route('shippers.store'));
  };

  return (
    <AuthenticatedLayout>
      <Head title="Create Shipper" />
      <div className="p-6">
        <h1 className="text-2xl font-bold mb-6">Create New Shipper</h1>
        <form onSubmit={handleSubmit} className="space-y-4 max-w-2xl">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input
              id="name"
              value={data.name}
              onChange={(e) => setData('name', e.target.value)}
              error={errors.name}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="mc_number">MC Number</Label>
            <Input
              id="mc_number"
              value={data.mc_number}
              onChange={(e) => setData('mc_number', e.target.value)}
              error={errors.mc_number}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="dot_number">DOT Number</Label>
            <Input
              id="dot_number"
              value={data.dot_number}
              onChange={(e) => setData('dot_number', e.target.value)}
              error={errors.dot_number}
            />
          </div>
          <div className="flex justify-end">
            <Button type="submit" disabled={processing}>
              Create Shipper
            </Button>
          </div>
        </form>
      </div>
    </AuthenticatedLayout>
  );
}

// resources/js/Pages/Shippers/Create.vue
<template>
  <div class="max-w-3xl mx-auto p-4">
    <h1 class="text-xl font-bold mb-6">Create New Shipper</h1>
    
    <form @submit.prevent="submitForm" class="space-y-4">
      <div>
        <label class="block mb-1 font-semibold">Name</label>
        <Input v-model="form.name" placeholder="Shipper Name" />
      </div>
      <div>
        <label class="block mb-1 font-semibold">City</label>
        <Input v-model="form.city" placeholder="City" />
      </div>
      <div>
        <label class="block mb-1 font-semibold">State</label>
        <Input v-model="form.state" placeholder="State/Province" />
      </div>
      <div>
        <label class="block mb-1 font-semibold">Country</label>
        <Input v-model="form.country" placeholder="Country" />
      </div>

      <Button type="submit">Create</Button>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue'
import { Inertia } from '@inertiajs/inertia'

export default defineComponent({
  setup() {
    const form = reactive({
      name: '',
      city: '',
      state: '',
      country: '',
    })

    function submitForm() {
      // Example Inertia post request to create a new shipper
      Inertia.post(route('shippers.store'), form, {
        onFinish: () => {
          // Possibly handle success or show a flash message
        },
      })
    }

    return {
      form,
      submitForm,
    }
  },
})
</script>
