// resources/js/Pages/Shippers/Index.tsx
import { Inertia, usePage } from '@inertiajs/inertia-react';
import { useState } from 'react';
import Skeleton from '@/components/Skeleton';
import { TabList, TabPanel, Tabs } from '@/components/Tabs';
import { Button, Input } from '@/components/ui';

interface Shipper {
  id: number;
  name: string;
  // other fields as needed
}

interface ShipperDetails {
  id: number;
  general: any;
  accounting: any;
  locations: any[];
  shipmentHistory: any[];
  contacts: any[];
  notes: any[];
  documents: any[];
}

const ShipperListPage = () => {
  const { shippers: initialShippers, shipper: initialShipperDetails } = usePage().props as {
    shippers: Shipper[];
    shipper?: ShipperDetails;
  };

  const [searchTerm, setSearchTerm] = useState('');
  const [selectedShipper, setSelectedShipper] = useState<Shipper | null>(null);
  const [shipperDetails, setShipperDetails] = useState<ShipperDetails | null>(initialShipperDetails || null);
  const [loadingDetails, setLoadingDetails] = useState(false);

  const filteredShippers = initialShippers.filter((shipper) =>
    shipper.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleRowClick = (shipper: Shipper) => {
    setSelectedShipper(shipper);
    setLoadingDetails(true);
    // Use Inertia partial reload to load detailed info about the selected shipper
    Inertia.get(
      route('shippers.details', shipper.id),
      {},
      {
        replace: true,
        preserveState: true,
        only: ['shipper'],
        onSuccess: (page: any) => {
          setShipperDetails(page.props.shipper);
          setLoadingDetails(false);
        },
        onError: () => {
          setLoadingDetails(false);
        }
      }
    );
  };

  return (
    <div className="flex h-full flex-col">
      <div className="p-4">
        <div className="mb-4 flex items-center justify-between">
          <h1 className="text-2xl font-bold">Shippers</h1>
          <Button onClick={() => Inertia.visit(route('shippers.create'))}>
            Add New Shipper
          </Button>
        </div>
        <Input
          type="text"
          placeholder="Search Shippers..."
          value={searchTerm}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearchTerm(e.target.value)}
        />
      </div>
      <div className="flex flex-col flex-1">
        <div className="overflow-auto" style={{ maxHeight: '50%' }}>
          <table className="min-w-full">
            <thead>
              <tr>
                <th className="px-4 py-2">ID</th>
                <th className="px-4 py-2">Name</th>
                {/* Additional columns as needed */}
              </tr>
            </thead>
            <tbody>
              {filteredShippers.map((shipper) => (
                <tr
                  key={shipper.id}
                  onClick={() => handleRowClick(shipper)}
                  className={`cursor-pointer ${selectedShipper?.id === shipper.id ? 'bg-blue-100' : ''}`}
                >
                  <td className="border px-4 py-2">{shipper.id}</td>
                  <td className="border px-4 py-2">{shipper.name}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex-1 overflow-auto border-t p-4">
          {loadingDetails ? (
            <Skeleton className="h-full" />
          ) : selectedShipper && shipperDetails ? (
            <div>
              <div className="mb-4 flex justify-between">
                <h2 className="text-xl font-semibold">{selectedShipper.name}</h2>
                <div className="space-x-2">
                  <Button onClick={() => Inertia.visit(route('shippers.loads', selectedShipper.id))}>
                    See Loads
                  </Button>
                  <Button onClick={() => Inertia.visit(route('shippers.edit', selectedShipper.id))}>
                    Edit
                  </Button>
                  <Button
                    onClick={() => {
                      // Trigger add note modal or action
                    }}
                  >
                    Add Note
                  </Button>
                  <Button
                    onClick={() => {
                      // Trigger add location modal or action
                    }}
                  >
                    Add Location
                  </Button>
                </div>
              </div>
              <Tabs>
                <TabList>
                  <li>General</li>
                  <li>Accounting</li>
                  <li>Locations</li>
                  <li>Shipment History</li>
                  <li>Contacts</li>
                  <li>Notes</li>
                  <li>Documents</li>
                </TabList>
                <TabPanel>
                  {shipperDetails.general ? shipperDetails.general : <Skeleton className="h-20" />}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.accounting ? shipperDetails.accounting : <Skeleton className="h-20" />}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.locations.length ? (
                    <ul>
                      {shipperDetails.locations.map((location, idx) => (
                        <li key={idx}>{location.address || 'Location'}</li>
                      ))}
                    </ul>
                  ) : (
                    <Skeleton className="h-20" />
                  )}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.shipmentHistory.length ? (
                    <ul>
                      {shipperDetails.shipmentHistory.map((shipment, idx) => (
                        <li key={idx}>Shipment {shipment.id}</li>
                      ))}
                    </ul>
                  ) : (
                    <Skeleton className="h-20" />
                  )}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.contacts.length ? (
                    <ul>
                      {shipperDetails.contacts.map((contact, idx) => (
                        <li key={idx}>{contact.name}</li>
                      ))}
                    </ul>
                  ) : (
                    <Skeleton className="h-20" />
                  )}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.notes.length ? (
                    <ul>
                      {shipperDetails.notes.map((note, idx) => (
                        <li key={idx}>{note.content}</li>
                      ))}
                    </ul>
                  ) : (
                    <Skeleton className="h-20" />
                  )}
                </TabPanel>
                <TabPanel>
                  {shipperDetails.documents.length ? (
                    <ul>
                      {shipperDetails.documents.map((doc, idx) => (
                        <li key={idx}>{doc.filename}</li>
                      ))}
                    </ul>
                  ) : (
                    <Skeleton className="h-20" />
                  )}
                </TabPanel>
              </Tabs>
            </div>
          ) : (
            <div className="text-gray-500">
              Select a shipper to see details.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ShipperListPage;

// resources/js/Pages/Shippers/Index.vue
<template>
  <div class="space-y-4">
    <!-- Page Header -->
    <div class="flex items-center justify-between">
      <h1 class="text-xl font-bold">Shipper Management</h1>
      <Button @click="goToCreateShipper">+ New Shipper</Button>
    </div>

    <!-- Table & Search -->
    <div class="bg-white p-4 rounded-md shadow">
      <div class="mb-2">
        <!-- Search bar for filtering shippers -->
        <Input
          type="text"
          placeholder="Search Shippers..."
          v-model="searchQuery"
          @input="searchShippers"
          class="w-full"
        />
      </div>
      <div class="overflow-x-auto">
        <!-- Shipper table -->
        <table class="table-auto w-full">
          <thead>
            <tr>
              <th class="px-4 py-2">Name</th>
              <th class="px-4 py-2">City</th>
              <th class="px-4 py-2">State</th>
              <th class="px-4 py-2">Country</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="shipper in filteredShippers"
              :key="shipper.id"
              :class="{'bg-gray-100': shipper.id === selectedShipperId}"
              @click="selectShipper(shipper.id)"
              class="cursor-pointer hover:bg-gray-50"
            >
              <td class="px-4 py-2">{{ shipper.name }}</td>
              <td class="px-4 py-2">{{ shipper.city }}</td>
              <td class="px-4 py-2">{{ shipper.state }}</td>
              <td class="px-4 py-2">{{ shipper.country }}</td>
            </tr>
          </tbody>
        </table>

        <!-- Skeleton loading (if needed) -->
        <skeleton v-if="loadingShippers" class="mt-4" />
      </div>
    </div>

    <!-- Selected Shipper Details -->
    <div class="bg-white rounded-md shadow p-4" v-if="selectedShipperData">
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-lg font-semibold">Shipper Details: {{ selectedShipperData.name }}</h2>
        <!-- Example button to list loads related to this shipper -->
        <Button @click="loadShipperLoads">View Loads</Button>
      </div>

      <!-- Tabs -->
      <div class="border-b mb-2 flex">
        <button
          v-for="tab in tabs"
          :key="tab"
          @click="activeTab = tab"
          :class="[
            'px-4 py-2',
            activeTab === tab ? 'border-b-2 border-blue-500 font-semibold' : ''
          ]"
        >
          {{ tab }}
        </button>
      </div>

      <!-- Tab Panels -->
      <div>
        <!-- General -->
        <div v-if="activeTab === 'General'">
          <p class="mb-2">[General Ship Information Here]</p>
          <Button class="mt-2" @click="editShipper">Edit Shipper</Button>
        </div>

        <!-- Accounting -->
        <div v-else-if="activeTab === 'Accounting'">
          <p>[Accounting Info Component Here]</p>
        </div>

        <!-- Locations -->
        <div v-else-if="activeTab === 'Locations'">
          <p>[Location List Component Here]</p>
          <Button class="mt-2" @click="addLocation">Add Location</Button>
        </div>

        <!-- Shipment History -->
        <div v-else-if="activeTab === 'Shipment History'">
          <p>[Shipment History for this Shipper]</p>
        </div>

        <!-- Contacts -->
        <div v-else-if="activeTab === 'Contacts'">
          <p>[Contacts Component]</p>
        </div>

        <!-- Notes -->
        <div v-else-if="activeTab === 'Notes'">
          <p>[Notes List Component]</p>
          <!-- Use something like the "Add note" UI from your shipment show page -->
          <Button class="mt-2" @click="addNote">Add Note</Button>
        </div>

        <!-- Documents -->
        <div v-else-if="activeTab === 'Documents'">
          <p>[Documents Component]</p>
        </div>
      </div>

      <!-- Skeleton loading (if needed) -->
      <skeleton v-else-if="loadingDetails" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted } from 'vue'
import { Inertia } from '@inertiajs/inertia'
// Import your existing UI components
// import Button from '@/Components/Button' 
// import Input from '@/Components/Input'
// import skeleton from '@/Components/Skeleton'

export default defineComponent({
  setup() {
    const loadingShippers = ref(false)
    const loadingDetails = ref(false)
    const shippers = ref<any[]>([])
    const selectedShipperId = ref<number | null>(null)
    const selectedShipperData = ref<any>(null)

    const searchQuery = ref('')
    const tabs = ['General', 'Accounting', 'Locations', 'Shipment History', 'Contacts', 'Notes', 'Documents']
    const activeTab = ref('General')

    onMounted(() => {
      // Load initial list of shippers
      loadShippers()
    })

    function loadShippers() {
      loadingShippers.value = true
      // Replace with your inertia or axios call
      setTimeout(() => {
        // Demo data
        shippers.value = [
          { id: 1, name: 'ABC Logistics', city: 'Seattle', state: 'WA', country: 'USA' },
          { id: 2, name: 'XYZ Freight', city: 'Portland', state: 'OR', country: 'USA' },
          // ...
        ]
        loadingShippers.value = false
      }, 1000)
    }

    function selectShipper(id: number) {
      selectedShipperId.value = id
      loadShipperDetails(id)
    }

    function loadShipperDetails(id: number) {
      loadingDetails.value = true
      // Example async load. Replace with your inertia partial reload or axios call
      setTimeout(() => {
        selectedShipperData.value = {
          id,
          name: 'Dummy Shipper Name',
          // ...
        }
        loadingDetails.value = false
      }, 500)
    }

    // Filter shippers by search query
    const filteredShippers = computed(() => {
      return shippers.value.filter(s =>
        s.name.toLowerCase().includes(searchQuery.value.toLowerCase())
      )
    })

    function searchShippers() {
      // Potentially an API call or just local filtering
    }

    function editShipper() {
      // Show an edit form or route to an Edit page
    }

    function addLocation() {
      // Show a dialog or route to a create location flow
    }

    function addNote() {
      // Show a dialog or inline form for adding a new note
    }

    function loadShipperLoads() {
      // A button to see a list of loads related to the shipper, filter loads by active or not
      // Possibly trigger a modal or route
    }

    function goToCreateShipper() {
      Inertia.get(route('shippers.create'))
    }

    return {
      loadingShippers,
      loadingDetails,
      shippers,
      searchQuery,
      filteredShippers,
      selectedShipperId,
      selectedShipperData,
      tabs,
      activeTab,
      selectShipper,
      searchShippers,
      editShipper,
      addLocation,
      addNote,
      loadShipperLoads,
      goToCreateShipper,
    }
  },
})
</script>
